ALTER TABLE WWW_Users DROP FOREIGN KEY WWW_Users_fk_SupplierID;
ALTER TABLE WWW_Users DROP FOREIGN KEY WWW_Users_fk_DefaultLocation;
ALTER TABLE WWW_Users DROP KEY `WWW_Users_fk_SupplierID`;
ALTER TABLE WWW_Users DROP KEY `WWW_Users_fk_DefaultLocation`;

ALTER TABLE WWW_Users DROP Password, DROP FullAccess, DROP ModulesAllowed, DROP Blocked, DROP DisplayRecordsMax, DROP Salt, CHANGE UserID UserID VARCHAR(20) NOT NULL, CHANGE DefaultLocation DefaultLocation VARCHAR(5) DEFAULT NULL;
ALTER TABLE WWW_Users ADD CONSTRAINT FK_A713D225AB3682CB FOREIGN KEY (SupplierID) REFERENCES Suppliers (SupplierID);
ALTER TABLE WWW_Users ADD CONSTRAINT FK_A713D225A9E0653B FOREIGN KEY (DefaultLocation) REFERENCES Locations (LocCode);
CREATE INDEX IDX_A713D225AB3682CB ON WWW_Users (SupplierID);
CREATE INDEX IDX_A713D225A9E0653B ON WWW_Users (DefaultLocation);
ALTER TABLE UserRole ADD CONSTRAINT FK_A8503F7364B64DCC FOREIGN KEY (userId) REFERENCES WWW_Users (UserID);
ALTER TABLE WWW_Users DROP INDEX FK_A713D22556EC1FCE, ADD UNIQUE INDEX UNIQ_A713D22556EC1FCE (branchID);
ALTER TABLE WWW_Users ADD dateFormat VARCHAR(10) DEFAULT 'Y-m-d' NOT NULL;
