# Configuration for production environment (gumstix.com)

imports:
    - { resource: config.yaml }

parameters:
    db_host: live-rialto-rds.c9kpdp26dpn1.us-west-2.rds.amazonaws.com
    mongo_host: 10.0.1.157
    data_bucket: gumstix-rialto-files

    # Set the default request context for generatings URLs in console commands
    router.request_context.host: rialto.gumstix.com
    router.request_context.scheme: https
    router.request_context.base_url: /index.php

    trusted_hosts:
        - gumstix.com
        - '%pcb_ng.storefront.base_uri%'
    cors_hosts:
        - ^https://(.+.)?gumstix.com
    use_ssl: true

    user.admin: gordon
    user.webmaster: ianfp

    ups.webservices.uri: https://onlinetools.ups.com
    ups.user_id: craighughes
    ups.invoice_host: ftp2.ups.com
    ups.invoice_username: gumstix0316

    authorizenet.login: GumStix01
    authorizenet.sandbox: 0

    pcb_ng.storefront.base_uri: 'https://order.pcb.ng/'
    pcb_ng.api.base_uri: 'https://api-201807.pcbng.com/api/'

    gumstix_sso.service.server: https://accounts.gumstix.com/
    rialto_wordpress.base_url: https://www.gumstix.com
    rialto_madison.madison_url: https://madison.gumstix.com/app.php
    catalina.base_url: https://catalina.gumstix.com
    geppetto.base_url: https://geppetto.gumstix.com


#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        sentry:
            type: raven
            dsn: "%sentry_dsn%"
            level: warning
            channels: "!flash"
        production:
            type: mongo
            mongo:
                host: "%mongo_host%"
                database: rialto
                collection: production
            level: info
            channels:
                - supplier
                - manufacturing
                - receiving
        automation:
            type: mongo
            mongo:
                host: "%mongo_host%"
                database: rialto
                collection: automation
            level: info
            channels:
                - automation
        email:
            type: mongo
            mongo:
                host: "%mongo_host%"
                database: rialto
                collection: email
            level: info
            channels:
                - email
        flash:
            type: service
            id: Rialto\Logging\FlashHandler
            channels: flash

        # Use logger for console command output.
        # See https://symfony.com/doc/current/cookbook/logging/monolog_console.html
        console:
            type: console
            level: info
            channels: "!doctrine"
