<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBq1mywm\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBq1mywm/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBq1mywm.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBq1mywm\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBq1mywm\appDevDebugProjectContainer([
    'container.build_hash' => 'Bq1mywm',
    'container.build_id' => '853e8b99',
    'container.build_time' => 1610556206,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBq1mywm');
