services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Rialto\Port\EventDispatcher\EventRecorderInterface:
        class: Infrastructure\EventDispatcher\SimpleEventRecorder
