<?php

namespace Proxies\__CG__\Rialto\Accounting\Terms;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PaymentTerms extends \Rialto\Accounting\Terms\PaymentTerms implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Rialto\\Accounting\\Terms\\PaymentTerms' . "\0" . 'id', '' . "\0" . 'Rialto\\Accounting\\Terms\\PaymentTerms' . "\0" . 'name', '' . "\0" . 'Rialto\\Accounting\\Terms\\PaymentTerms' . "\0" . 'daysBeforeDue', '' . "\0" . 'Rialto\\Accounting\\Terms\\PaymentTerms' . "\0" . 'dayInFollowingMonth'];
        }

        return ['__isInitialized__', '' . "\0" . 'Rialto\\Accounting\\Terms\\PaymentTerms' . "\0" . 'id', '' . "\0" . 'Rialto\\Accounting\\Terms\\PaymentTerms' . "\0" . 'name', '' . "\0" . 'Rialto\\Accounting\\Terms\\PaymentTerms' . "\0" . 'daysBeforeDue', '' . "\0" . 'Rialto\\Accounting\\Terms\\PaymentTerms' . "\0" . 'dayInFollowingMonth'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PaymentTerms $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getDaysBeforeDue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDaysBeforeDue', []);

        return parent::getDaysBeforeDue();
    }

    /**
     * {@inheritDoc}
     */
    public function setDaysBeforeDue($days)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDaysBeforeDue', [$days]);

        return parent::setDaysBeforeDue($days);
    }

    /**
     * {@inheritDoc}
     */
    public function getDayInFollowingMonth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDayInFollowingMonth', []);

        return parent::getDayInFollowingMonth();
    }

    /**
     * {@inheritDoc}
     */
    public function setDayInFollowingMonth($day)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDayInFollowingMonth', [$day]);

        return parent::setDayInFollowingMonth($day);
    }

    /**
     * {@inheritDoc}
     */
    public function calculateDueDate(\DateTime $from)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'calculateDueDate', [$from]);

        return parent::calculateDueDate($from);
    }

}
