<?php

namespace Proxies\__CG__\Rialto\Sales\Customer;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CustomerBranch extends \Rialto\Sales\Customer\CustomerBranch implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'id', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'customer', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'branchCode', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'branchName', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'address', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'contactPhone', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'fax', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'contactName', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'email', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'taxAuthority', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'deniedPartyExemption', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'customerBranchCode', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'salesman', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'salesArea', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'defaultLocation', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'defaultShipper'];
        }

        return ['__isInitialized__', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'id', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'customer', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'branchCode', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'branchName', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'address', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'contactPhone', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'fax', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'contactName', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'email', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'taxAuthority', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'deniedPartyExemption', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'customerBranchCode', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'salesman', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'salesArea', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'defaultLocation', '' . "\0" . 'Rialto\\Sales\\Customer\\CustomerBranch' . "\0" . 'defaultShipper'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CustomerBranch $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function equals(\Rialto\Sales\Customer\CustomerBranch $other)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'equals', [$other]);

        return parent::equals($other);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomer', []);

        return parent::getCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function isInternalCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isInternalCustomer', []);

        return parent::isInternalCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function getArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArea', []);

        return parent::getArea();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getBranchCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBranchCode', []);

        return parent::getBranchCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setBranchCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBranchCode', [$code]);

        return parent::setBranchCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getBranchName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBranchName', []);

        return parent::getBranchName();
    }

    /**
     * {@inheritDoc}
     */
    public function getContactName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactName', []);

        return parent::getContactName();
    }

    /**
     * {@inheritDoc}
     */
    public function getLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', []);

        return parent::getLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getContactPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactPhone', []);

        return parent::getContactPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', []);

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress(\Rialto\Geography\Address\Address $address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getStreet1(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreet1', []);

        return parent::getStreet1();
    }

    /**
     * {@inheritDoc}
     */
    public function getStreet2(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreet2', []);

        return parent::getStreet2();
    }

    /**
     * {@inheritDoc}
     */
    public function getMailStop(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailStop', []);

        return parent::getMailStop();
    }

    /**
     * {@inheritDoc}
     */
    public function getCity(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function getPostalCode(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostalCode', []);

        return parent::getPostalCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getStateCode(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStateCode', []);

        return parent::getStateCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getStateName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStateName', []);

        return parent::getStateName();
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function getCountryCode(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountryCode', []);

        return parent::getCountryCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getCountryName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountryName', []);

        return parent::getCountryName();
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerBranchCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerBranchCode', []);

        return parent::getCustomerBranchCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerId', []);

        return parent::getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultLocation', []);

        return parent::getDefaultLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultShipper()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultShipper', []);

        return parent::getDefaultShipper();
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxId', []);

        return parent::getTaxId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxAuthority(): \Rialto\Tax\Authority\TaxAuthority
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxAuthority', []);

        return parent::getTaxAuthority();
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxAccount(): \Rialto\Accounting\Ledger\Account\GLAccount
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxAccount', []);

        return parent::getTaxAccount();
    }

    /**
     * {@inheritDoc}
     */
    public function resetTaxAuthority(\Rialto\Database\Orm\DbManager $dbm): \Rialto\Sales\Customer\CustomerBranch
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'resetTaxAuthority', [$dbm]);

        return parent::resetTaxAuthority($dbm);
    }

    /**
     * {@inheritDoc}
     */
    public function isTaxExempt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isTaxExempt', []);

        return parent::isTaxExempt();
    }

    /**
     * {@inheritDoc}
     */
    public function setBranchName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBranchName', [$name]);

        return parent::setBranchName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setContactName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactName', [$name]);

        return parent::setContactName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerBranchCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerBranchCode', [$code]);

        return parent::setCustomerBranchCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function setDefaultShipper(\Rialto\Shipping\Shipper\Shipper $shipper)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDefaultShipper', [$shipper]);

        return parent::setDefaultShipper($shipper);
    }

    /**
     * {@inheritDoc}
     */
    public function setContactPhone($phoneNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactPhone', [$phoneNo]);

        return parent::setContactPhone($phoneNo);
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($faxNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', [$faxNo]);

        return parent::setFax($faxNo);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxAuthority(\Rialto\Tax\Authority\TaxAuthority $tax = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxAuthority', [$tax]);

        return parent::setTaxAuthority($tax);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalesman()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalesman', []);

        return parent::getSalesman();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalesman(\Rialto\Sales\Salesman\Salesman $salesman)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalesman', [$salesman]);

        return parent::setSalesman($salesman);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalesArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalesArea', []);

        return parent::getSalesArea();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalesArea(\Rialto\Sales\Customer\SalesArea $area)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalesArea', [$area]);

        return parent::setSalesArea($area);
    }

    /**
     * {@inheritDoc}
     */
    public function setDefaultLocation(\Rialto\Stock\Facility\Facility $location)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDefaultLocation', [$location]);

        return parent::setDefaultLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function isNew()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isNew', []);

        return parent::isNew();
    }

    /**
     * {@inheritDoc}
     */
    public function isDeniedPartyExempt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDeniedPartyExempt', []);

        return parent::isDeniedPartyExempt();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeniedPartyExemption()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeniedPartyExemption', []);

        return parent::getDeniedPartyExemption();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeniedPartyExemption($reason)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeniedPartyExemption', [$reason]);

        return parent::setDeniedPartyExemption($reason);
    }

}
