<?php

namespace Proxies\__CG__\Rialto\Purchasing\Supplier;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Supplier extends \Rialto\Purchasing\Supplier\Supplier implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'id', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'name', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'orderAddress', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'paymentAddress', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'supplierSince', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'customerAccount', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'customerNumber', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'lastPaid', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'lastPaidDate', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'bankAccount', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'bankReference', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'bankParticulars', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'remittanceAdviceRequired', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'website', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'facility', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'currency', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'paymentTerms', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'contacts', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'taxAuthority', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'parent', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'manufacturer', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'attributes'];
        }

        return ['__isInitialized__', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'id', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'name', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'orderAddress', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'paymentAddress', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'supplierSince', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'customerAccount', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'customerNumber', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'lastPaid', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'lastPaidDate', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'bankAccount', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'bankReference', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'bankParticulars', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'remittanceAdviceRequired', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'website', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'facility', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'currency', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'paymentTerms', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'contacts', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'taxAuthority', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'parent', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'manufacturer', '' . "\0" . 'Rialto\\Purchasing\\Supplier\\Supplier' . "\0" . 'attributes'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Supplier $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function createPurchasingData(\Rialto\Stock\Item\StockItem $stockItem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'createPurchasingData', [$stockItem]);

        return parent::createPurchasingData($stockItem);
    }

    /**
     * {@inheritDoc}
     */
    public function getContacts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContacts', []);

        return parent::getContacts();
    }

    /**
     * {@inheritDoc}
     */
    public function getActiveContacts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActiveContacts', []);

        return parent::getActiveContacts();
    }

    /**
     * {@inheritDoc}
     */
    public function getKitContacts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKitContacts', []);

        return parent::getKitContacts();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderContacts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderContacts', []);

        return parent::getOrderContacts();
    }

    /**
     * {@inheritDoc}
     */
    public function getFacility()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacility', []);

        return parent::getFacility();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacility(\Rialto\Stock\Facility\Facility $facility)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacility', [$facility]);

        return parent::setFacility($facility);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', []);

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation(\Rialto\Stock\Facility\Facility $facility)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', [$facility]);

        return parent::setLocation($facility);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function equals(\Rialto\Purchasing\Supplier\Supplier $other = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'equals', [$other]);

        return parent::equals($other);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', []);

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent(\Rialto\Purchasing\Supplier\Supplier $parent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', [$parent]);

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function isSubsidiaryOf(\Rialto\Purchasing\Supplier\Supplier $other = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSubsidiaryOf', [$other]);

        return parent::isSubsidiaryOf($other);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', []);

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrency(\Rialto\Accounting\Currency\Currency $currency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrency', [$currency]);

        return parent::setCurrency($currency);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupplierSince()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupplierSince', []);

        return parent::getSupplierSince();
    }

    /**
     * {@inheritDoc}
     */
    public function setSupplierSince(\DateTime $date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupplierSince', [$date]);

        return parent::setSupplierSince($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerNumber', []);

        return parent::getCustomerNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerNumber($number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerNumber', [$number]);

        return parent::setCustomerNumber($number);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerAccount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerAccount', []);

        return parent::getCustomerAccount();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerAccount($account)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerAccount', [$account]);

        return parent::setCustomerAccount($account);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankAccount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankAccount', []);

        return parent::getBankAccount();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankAccount($account)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankAccount', [$account]);

        return parent::setBankAccount($account);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankReference', []);

        return parent::getBankReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankReference($ref)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankReference', [$ref]);

        return parent::setBankReference($ref);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankParticulars()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankParticulars', []);

        return parent::getBankParticulars();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankParticulars($particulars)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankParticulars', [$particulars]);

        return parent::setBankParticulars($particulars);
    }

    /**
     * {@inheritDoc}
     */
    public function isRemittanceAdviceRequired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isRemittanceAdviceRequired', []);

        return parent::isRemittanceAdviceRequired();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemittanceAdviceRequired($remittance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemittanceAdviceRequired', [$remittance]);

        return parent::setRemittanceAdviceRequired($remittance);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxAuthority()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxAuthority', []);

        return parent::getTaxAuthority();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxAuthority(\Rialto\Tax\Authority\TaxAuthority $auth = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxAuthority', [$auth]);

        return parent::setTaxAuthority($auth);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsite', []);

        return parent::getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsite($website)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsite', [$website]);

        return parent::setWebsite($website);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomainName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomainName', []);

        return parent::getDomainName();
    }

    /**
     * {@inheritDoc}
     */
    public function getSearchUrl($query = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSearchUrl', [$query]);

        return parent::getSearchUrl($query);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentTerms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentTerms', []);

        return parent::getPaymentTerms();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentTerms(\Rialto\Accounting\Terms\PaymentTerms $terms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentTerms', [$terms]);

        return parent::setPaymentTerms($terms);
    }

    /**
     * {@inheritDoc}
     */
    public function getPurchasingData(\Rialto\Stock\Item $item)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPurchasingData', [$item]);

        return parent::getPurchasingData($item);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastPaid($amount, \DateTime $date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastPaid', [$amount, $date]);

        return parent::setLastPaid($amount, $date);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderAddress', []);

        return parent::getOrderAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderAddress(\Rialto\Geography\Address\Address $address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderAddress', [$address]);

        return parent::setOrderAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentAddress', []);

        return parent::getPaymentAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentAddress(\Rialto\Geography\Address\Address $address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentAddress', [$address]);

        return parent::setPaymentAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderAddressStreet1(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderAddressStreet1', []);

        return parent::getOrderAddressStreet1();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderAddressStreet2(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderAddressStreet2', []);

        return parent::getOrderAddressStreet2();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderAddressMailStop(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderAddressMailStop', []);

        return parent::getOrderAddressMailStop();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderAddressCity(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderAddressCity', []);

        return parent::getOrderAddressCity();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderAddressStateCode(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderAddressStateCode', []);

        return parent::getOrderAddressStateCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderAddressStateName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderAddressStateName', []);

        return parent::getOrderAddressStateName();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderAddressPostalCode(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderAddressPostalCode', []);

        return parent::getOrderAddressPostalCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderAddressCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderAddressCountry', []);

        return parent::getOrderAddressCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderAddressCountryCode(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderAddressCountryCode', []);

        return parent::getOrderAddressCountryCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getCountryName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountryName', []);

        return parent::getCountryName();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentAddressStreet1(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentAddressStreet1', []);

        return parent::getPaymentAddressStreet1();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentAddressStreet2(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentAddressStreet2', []);

        return parent::getPaymentAddressStreet2();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentAddressMailStop(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentAddressMailStop', []);

        return parent::getPaymentAddressMailStop();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentAddressCity(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentAddressCity', []);

        return parent::getPaymentAddressCity();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentAddressStateCode(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentAddressStateCode', []);

        return parent::getPaymentAddressStateCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentAddressStateName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentAddressStateName', []);

        return parent::getPaymentAddressStateName();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentAddressPostalCode(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentAddressPostalCode', []);

        return parent::getPaymentAddressPostalCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentAddressCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentAddressCountry', []);

        return parent::getPaymentAddressCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentAddressCountryCode(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentAddressCountryCode', []);

        return parent::getPaymentAddressCountryCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentAddressCountryName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentAddressCountryName', []);

        return parent::getPaymentAddressCountryName();
    }

    /**
     * {@inheritDoc}
     */
    public function getManufacturer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManufacturer', []);

        return parent::getManufacturer();
    }

}
