<?php

namespace Proxies\__CG__\Rialto\Purchasing\Catalog;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PurchasingData extends \Rialto\Purchasing\Catalog\PurchasingData implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'id', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'stockItem', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'supplier', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'buildLocation', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'catalogNumber', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'quotationNumber', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'version', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'manufacturer', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'manufacturerCode', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'suppliersUOM', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'conversionFactor', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'binStyle', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'supplierDescription', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'preferred', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'rohs', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'temperature', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'turnkey', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'incrementQty', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'binSize', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'costBreaks', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'stockLevel', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'lastSync', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'productUrl', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'endOfLife'];
        }

        return ['__isInitialized__', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'id', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'stockItem', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'supplier', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'buildLocation', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'catalogNumber', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'quotationNumber', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'version', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'manufacturer', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'manufacturerCode', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'suppliersUOM', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'conversionFactor', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'binStyle', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'supplierDescription', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'preferred', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'rohs', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'temperature', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'turnkey', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'incrementQty', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'binSize', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'costBreaks', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'stockLevel', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'lastSync', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'productUrl', '' . "\0" . 'Rialto\\Purchasing\\Catalog\\PurchasingData' . "\0" . 'endOfLife'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PurchasingData $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function isNew()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isNew', []);

        return parent::isNew();
    }

    /**
     * {@inheritDoc}
     */
    public function getLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', []);

        return parent::getLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function getCatalogNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCatalogNumber', []);

        return parent::getCatalogNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setCatalogNumber($catalogNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCatalogNumber', [$catalogNo]);

        return parent::setCatalogNumber($catalogNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuotationNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuotationNumber', []);

        return parent::getQuotationNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuotationNumber($quoteNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuotationNumber', [$quoteNo]);

        return parent::setQuotationNumber($quoteNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getStockItem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStockItem', []);

        return parent::getStockItem();
    }

    /**
     * {@inheritDoc}
     */
    public function getSku()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSku', []);

        return parent::getSku();
    }

    /**
     * {@inheritDoc}
     */
    public function getStockCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStockCode', []);

        return parent::getStockCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersion', []);

        return parent::getVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersion(\Rialto\Stock\Item\Version\Version $version)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersion', [$version]);

        return parent::setVersion($version);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpecifiedVersion(\Rialto\Stock\Item\Version\Version $version = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpecifiedVersion', [$version]);

        return parent::getSpecifiedVersion($version);
    }

    /**
     * {@inheritDoc}
     */
    public function supportsVersion(\Rialto\Stock\Item\Version\Version $version)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'supportsVersion', [$version]);

        return parent::supportsVersion($version);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupplier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupplier', []);

        return parent::getSupplier();
    }

    /**
     * {@inheritDoc}
     */
    public function hasSupplier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasSupplier', []);

        return parent::hasSupplier();
    }

    /**
     * {@inheritDoc}
     */
    public function setSupplier(\Rialto\Purchasing\Supplier\Supplier $supplier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupplier', [$supplier]);

        return parent::setSupplier($supplier);
    }

    /**
     * {@inheritDoc}
     */
    public function getBuildLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBuildLocation', []);

        return parent::getBuildLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', []);

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function validateSupplier(\Symfony\Component\Validator\Context\ExecutionContextInterface $context)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'validateSupplier', [$context]);

        return parent::validateSupplier($context);
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation(\Rialto\Stock\Facility\Facility $buildLocation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', [$buildLocation]);

        return parent::setLocation($buildLocation);
    }

    /**
     * {@inheritDoc}
     */
    public function setBuildLocation(\Rialto\Stock\Facility\Facility $buildLocation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBuildLocation', [$buildLocation]);

        return parent::setBuildLocation($buildLocation);
    }

    /**
     * {@inheritDoc}
     */
    public function isActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActive', []);

        return parent::isActive();
    }

    /**
     * {@inheritDoc}
     */
    public function getSupplierName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupplierName', []);

        return parent::getSupplierName();
    }

    /**
     * {@inheritDoc}
     */
    public function getSupplierSummary()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupplierSummary', []);

        return parent::getSupplierSummary();
    }

    /**
     * {@inheritDoc}
     */
    public function getSupplierDomainName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupplierDomainName', []);

        return parent::getSupplierDomainName();
    }

    /**
     * {@inheritDoc}
     */
    public function getSupplierSearchUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupplierSearchUrl', []);

        return parent::getSupplierSearchUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function getCostBreaks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCostBreaks', []);

        return parent::getCostBreaks();
    }

    /**
     * {@inheritDoc}
     */
    public function createCostBreak($orderQty, $unitCost, $manLeadTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'createCostBreak', [$orderQty, $unitCost, $manLeadTime]);

        return parent::createCostBreak($orderQty, $unitCost, $manLeadTime);
    }

    /**
     * {@inheritDoc}
     */
    public function addCostBreak(\Rialto\Purchasing\Catalog\CostBreak $cost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCostBreak', [$cost]);

        return parent::addCostBreak($cost);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCostBreak(\Rialto\Purchasing\Catalog\CostBreak $cost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCostBreak', [$cost]);

        return parent::removeCostBreak($cost);
    }

    /**
     * {@inheritDoc}
     */
    public function setCostBreaks(array $breaks)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCostBreaks', [$breaks]);

        return parent::setCostBreaks($breaks);
    }

    /**
     * {@inheritDoc}
     */
    public function clearCostBreaks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearCostBreaks', []);

        return parent::clearCostBreaks();
    }

    /**
     * {@inheritDoc}
     */
    public function validateCostBreaks(\Symfony\Component\Validator\Context\ExecutionContextInterface $context)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'validateCostBreaks', [$context]);

        return parent::validateCostBreaks($context);
    }

    /**
     * {@inheritDoc}
     */
    public function getCostLevels()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCostLevels', []);

        return parent::getCostLevels();
    }

    /**
     * {@inheritDoc}
     */
    public function addCostLevel(\Rialto\Purchasing\Catalog\CostBreak $cost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCostLevel', [$cost]);

        return parent::addCostLevel($cost);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCostLevel(\Rialto\Purchasing\Catalog\CostBreak $cost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCostLevel', [$cost]);

        return parent::removeCostLevel($cost);
    }

    /**
     * {@inheritDoc}
     */
    public function getLowestCostBreak($orderQty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLowestCostBreak', [$orderQty]);

        return parent::getLowestCostBreak($orderQty);
    }

    /**
     * {@inheritDoc}
     */
    public function getCost($orderQty = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCost', [$orderQty]);

        return parent::getCost($orderQty);
    }

    /**
     * {@inheritDoc}
     */
    public function getEoq()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEoq', []);

        return parent::getEoq();
    }

    /**
     * {@inheritDoc}
     */
    public function getEconomicOrderQty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEconomicOrderQty', []);

        return parent::getEconomicOrderQty();
    }

    /**
     * {@inheritDoc}
     */
    public function getMinimumOrderQty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinimumOrderQty', []);

        return parent::getMinimumOrderQty();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultOrderQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultOrderQuantity', []);

        return parent::getDefaultOrderQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function getCostAtEoq()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCostAtEoq', []);

        return parent::getCostAtEoq();
    }

    /**
     * {@inheritDoc}
     */
    public function getCostAtMoq(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCostAtMoq', []);

        return parent::getCostAtMoq();
    }

    /**
     * {@inheritDoc}
     */
    public function getMinimumOrderExtendedCost(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinimumOrderExtendedCost', []);

        return parent::getMinimumOrderExtendedCost();
    }

    /**
     * {@inheritDoc}
     */
    public function getStandardCost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStandardCost', []);

        return parent::getStandardCost();
    }

    /**
     * {@inheritDoc}
     */
    public function getLeadTime($orderQty = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeadTime', [$orderQty]);

        return parent::getLeadTime($orderQty);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeadTimeAtEoq()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeadTimeAtEoq', []);

        return parent::getLeadTimeAtEoq();
    }

    /**
     * {@inheritDoc}
     */
    public function getManufacturerLeadTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManufacturerLeadTime', []);

        return parent::getManufacturerLeadTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setManufacturerLeadTime($days)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManufacturerLeadTime', [$days]);

        return parent::setManufacturerLeadTime($days);
    }

    /**
     * {@inheritDoc}
     */
    public function getBinStyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBinStyle', []);

        return parent::getBinStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function setBinStyle(\Rialto\Stock\Bin\BinStyle $binStyle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBinStyle', [$binStyle]);

        return parent::setBinStyle($binStyle);
    }

    /**
     * {@inheritDoc}
     */
    public function getManufacturer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManufacturer', []);

        return parent::getManufacturer();
    }

    /**
     * {@inheritDoc}
     */
    public function setManufacturer(\Rialto\Purchasing\Manufacturer\Manufacturer $manufacturer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManufacturer', [$manufacturer]);

        return parent::setManufacturer($manufacturer);
    }

    /**
     * {@inheritDoc}
     */
    public function initManufacturer(\Rialto\Purchasing\Manufacturer\Manufacturer $manufacturer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'initManufacturer', [$manufacturer]);

        return parent::initManufacturer($manufacturer);
    }

    /**
     * {@inheritDoc}
     */
    public function validateManufacturer(\Symfony\Component\Validator\Context\ExecutionContextInterface $context)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'validateManufacturer', [$context]);

        return parent::validateManufacturer($context);
    }

    /**
     * {@inheritDoc}
     */
    public function getManufacturerCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManufacturerCode', []);

        return parent::getManufacturerCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getBinSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBinSize', []);

        return parent::getBinSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setBinSize($binSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBinSize', [$binSize]);

        return parent::setBinSize($binSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getIncrementQty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIncrementQty', []);

        return parent::getIncrementQty();
    }

    /**
     * {@inheritDoc}
     */
    public function setIncrementQty($qty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIncrementQty', [$qty]);

        return parent::setIncrementQty($qty);
    }

    /**
     * {@inheritDoc}
     */
    public function roundOrderQty($orderQty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'roundOrderQty', [$orderQty]);

        return parent::roundOrderQty($orderQty);
    }

    /**
     * {@inheritDoc}
     */
    public function getQtyAvailable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtyAvailable', []);

        return parent::getQtyAvailable();
    }

    /**
     * {@inheritDoc}
     */
    public function setQtyAvailable($qty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtyAvailable', [$qty]);

        return parent::setQtyAvailable($qty);
    }

    /**
     * {@inheritDoc}
     */
    public function getStockLevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStockLevel', []);

        return parent::getStockLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setStockLevel($stockLevel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStockLevel', [$stockLevel]);

        return parent::setStockLevel($stockLevel);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastSync()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastSync', []);

        return parent::getLastSync();
    }

    /**
     * {@inheritDoc}
     */
    public function isUpdatedSince($interval)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isUpdatedSince', [$interval]);

        return parent::isUpdatedSince($interval);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductUrl', []);

        return parent::getProductUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductUrl($productUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductUrl', [$productUrl]);

        return parent::setProductUrl($productUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function initProductUrl($productUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'initProductUrl', [$productUrl]);

        return parent::initProductUrl($productUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getTemperature()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTemperature', []);

        return parent::getTemperature();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoHS()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoHS', []);

        return parent::getRoHS();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoHS($RoHS)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoHS', [$RoHS]);

        return parent::setRoHS($RoHS);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuppliersUOM()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuppliersUOM', []);

        return parent::getSuppliersUOM();
    }

    /**
     * {@inheritDoc}
     */
    public function getSupplierDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupplierDescription', []);

        return parent::getSupplierDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getItemName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemName', []);

        return parent::getItemName();
    }

    /**
     * {@inheritDoc}
     */
    public function getConversionFactor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConversionFactor', []);

        return parent::getConversionFactor();
    }

    /**
     * {@inheritDoc}
     */
    public function isPreferred()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPreferred', []);

        return parent::isPreferred();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreferred(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreferred', []);

        parent::setPreferred();
    }

    /**
     * {@inheritDoc}
     */
    public function isTurnkey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isTurnkey', []);

        return parent::isTurnkey();
    }

    /**
     * {@inheritDoc}
     */
    public function isManufactured()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isManufactured', []);

        return parent::isManufactured();
    }

    /**
     * {@inheritDoc}
     */
    public function setManufacturerCode($manufacturerCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManufacturerCode', [$manufacturerCode]);

        return parent::setManufacturerCode($manufacturerCode);
    }

    /**
     * {@inheritDoc}
     */
    public function setSuppliersUOM($suppliersUOM)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuppliersUOM', [$suppliersUOM]);

        return parent::setSuppliersUOM($suppliersUOM);
    }

    /**
     * {@inheritDoc}
     */
    public function setConversionFactor($conversionFactor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConversionFactor', [$conversionFactor]);

        return parent::setConversionFactor($conversionFactor);
    }

    /**
     * {@inheritDoc}
     */
    public function setSupplierDescription($desc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupplierDescription', [$desc]);

        return parent::setSupplierDescription($desc);
    }

    /**
     * {@inheritDoc}
     */
    public function setTemperature($temperature)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTemperature', [$temperature]);

        return parent::setTemperature($temperature);
    }

    /**
     * {@inheritDoc}
     */
    public function setTurnkey($turnkey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTurnkey', [$turnkey]);

        return parent::setTurnkey($turnkey);
    }

    /**
     * {@inheritDoc}
     */
    public function setEndOfLife(\DateTime $endOfLife = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndOfLife', [$endOfLife]);

        return parent::setEndOfLife($endOfLife);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndOfLife()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndOfLife', []);

        return parent::getEndOfLife();
    }

    /**
     * {@inheritDoc}
     */
    public function isEndOfLife()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEndOfLife', []);

        return parent::isEndOfLife();
    }

    /**
     * {@inheritDoc}
     */
    public function importStockLevel(\Rialto\Purchasing\Catalog\CatalogItem $item)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'importStockLevel', [$item]);

        return parent::importStockLevel($item);
    }

    /**
     * {@inheritDoc}
     */
    public function importAllFields(\Rialto\Purchasing\Catalog\CatalogItem $entry)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'importAllFields', [$entry]);

        return parent::importAllFields($entry);
    }

}
