services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  Rialto\Geppetto\GeppettoClient:
    arguments:
      - "@gumstix_sso.http_client_factory"
      - "%geppetto.base_url%"

  Rialto\Geppetto\Design\DesignFactory:
    public: true

  Rialto\Geppetto\Design\DesignStockItemFactory: ~

  Rialto\Geppetto\Design\DesignStockItemTemplateFactory: ~

  Rialto\Geppetto\Design\Web\DesignController:
    tags: ['controller.service_arguments']

  Rialto\Geppetto\StandardCostListener: ~
