services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  Rialto\Sales\Returns\Receipt\SalesReturnReceiver:
    public: true

  Rialto\Sales\Returns\Disposition\SalesReturnDisposition:
    public: true
