<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Payment\AuthorizeNet' shared autowired service.

$this->services['Rialto\\Payment\\AuthorizeNet'] = $instance = new \Rialto\Payment\AuthorizeNet(new \Rialto\Payment\AuthorizeNetFactory('6e79LeRw', ''), ${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'});

$instance->setSandbox(1);

return $instance;
