<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Purchasing\Order\AutoSendReworkOrderSubscriber' shared autowired service.

return $this->services['Rialto\\Purchasing\\Order\\AutoSendReworkOrderSubscriber'] = new \Rialto\Purchasing\Order\AutoSendReworkOrderSubscriber(${($_ = isset($this->services['Rialto\\Purchasing\\Order\\OrderPdfGenerator']) ? $this->services['Rialto\\Purchasing\\Order\\OrderPdfGenerator'] : $this->load('getOrderPdfGeneratorService.php')) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Purchasing\\Order\\Attachment\\PurchaseOrderAttachmentGenerator']) ? $this->services['Rialto\\Purchasing\\Order\\Attachment\\PurchaseOrderAttachmentGenerator'] : $this->load('getPurchaseOrderAttachmentGeneratorService.php')) && false ?: '_'}, ${($_ = isset($this->services['templating']) ? $this->services['templating'] : $this->load('getTemplatingService.php')) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Email\\MailerInterface']) ? $this->services['Rialto\\Email\\MailerInterface'] : $this->load('getMailerInterfaceService.php')) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Cms\\CmsEngine']) ? $this->services['Rialto\\Cms\\CmsEngine'] : $this->getCmsEngineService()) && false ?: '_'});
