<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Shipping\Export\AllowedCountryValidator' shared autowired service.

return $this->services['Rialto\\Shipping\\Export\\AllowedCountryValidator'] = new \Rialto\Shipping\Export\AllowedCountryValidator(${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'});
