<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Stock\Shelf\Position\AssignmentListener' shared autowired service.

return $this->services['Rialto\\Stock\\Shelf\\Position\\AssignmentListener'] = new \Rialto\Stock\Shelf\Position\AssignmentListener(${($_ = isset($this->services['Rialto\\Stock\\Shelf\\Position\\PositionAssigner']) ? $this->services['Rialto\\Stock\\Shelf\\Position\\PositionAssigner'] : $this->load('getPositionAssignerService.php')) && false ?: '_'});
