<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Allocation\Allocation\AllocationTransferListener' shared autowired service.

return $this->services['Rialto\\Allocation\\Allocation\\AllocationTransferListener'] = new \Rialto\Allocation\Allocation\AllocationTransferListener(new \Rialto\Allocation\Allocation\AllocationTransfer());
