<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Sales\Shipping\ApproveToShipEventListener' shared autowired service.

return $this->services['Rialto\\Sales\\Shipping\\ApproveToShipEventListener'] = new \Rialto\Sales\Shipping\ApproveToShipEventListener(${($_ = isset($this->services['Rialto\\Sales\\Shipping\\SalesOrderShippingApproval']) ? $this->services['Rialto\\Sales\\Shipping\\SalesOrderShippingApproval'] : $this->load('getSalesOrderShippingApprovalService.php')) && false ?: '_'}, ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'});
