<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Manufacturing\Audit\AuditAdjuster' shared autowired service.

$a = ${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'};

$this->services['Rialto\\Manufacturing\\Audit\\AuditAdjuster'] = $instance = new \Rialto\Manufacturing\Audit\AuditAdjuster($a);

$b = ${($_ = isset($this->services['Rialto\\Allocation\\Allocation\\AllocationFactory']) ? $this->services['Rialto\\Allocation\\Allocation\\AllocationFactory'] : ($this->services['Rialto\\Allocation\\Allocation\\AllocationFactory'] = new \Rialto\Allocation\Allocation\AllocationFactory())) && false ?: '_'};

$c = new \Rialto\Manufacturing\Audit\Adjustment\AdjustPlaceholders($a, $b);

$instance->addReleaseStrategy($c);
$instance->addAcquireStrategy(new \Rialto\Manufacturing\Audit\Adjustment\UseAvailableStock($a, $b));
$instance->addAcquireStrategy($c);
$instance->addAcquireStrategy(new \Rialto\Manufacturing\Audit\Adjustment\AdjustCompetitors($a, $b));

return $instance;
