<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Panelization\AssetManager' shared autowired service.

return $this->services['Rialto\\Panelization\\AssetManager'] = new \Rialto\Panelization\AssetManager(${($_ = isset($this->services['Gumstix\\Storage\\FileStorage']) ? $this->services['Gumstix\\Storage\\FileStorage'] : $this->getFileStorageService()) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Panelization\\Web\\PanelPdfGenerator']) ? $this->services['Rialto\\Panelization\\Web\\PanelPdfGenerator'] : $this->load('getPanelPdfGeneratorService.php')) && false ?: '_'});
