<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Sales\Order\Allocation\AllocationEventListener' shared autowired service.

return $this->services['Rialto\\Sales\\Order\\Allocation\\AllocationEventListener'] = new \Rialto\Sales\Order\Allocation\AllocationEventListener(${($_ = isset($this->services['Rialto\\Allocation\\Allocation\\AllocationFactory']) ? $this->services['Rialto\\Allocation\\Allocation\\AllocationFactory'] : ($this->services['Rialto\\Allocation\\Allocation\\AllocationFactory'] = new \Rialto\Allocation\Allocation\AllocationFactory())) && false ?: '_'}, ${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'}, ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'});
