<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Purchasing\Manufacturer\Cli\BulkPushModuleManufacturersConsoleCommand' shared autowired service.

$a = ${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'};

$this->services['Rialto\\Purchasing\\Manufacturer\\Cli\\BulkPushModuleManufacturersConsoleCommand'] = $instance = new \Rialto\Purchasing\Manufacturer\Cli\BulkPushModuleManufacturersConsoleCommand($a, new \Rialto\Purchasing\Manufacturer\Command\PushManufacturerFeatureHandler($a, ${($_ = isset($this->services['Rialto\\Madison\\Feature\\StockItemFeatureCalculator']) ? $this->services['Rialto\\Madison\\Feature\\StockItemFeatureCalculator'] : $this->load('getStockItemFeatureCalculatorService.php')) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Madison\\MadisonClient']) ? $this->services['Rialto\\Madison\\MadisonClient'] : $this->load('getMadisonClientService.php')) && false ?: '_'}));

$instance->setName('purchasing:push-module-manufacturers');

return $instance;
