<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Security\Firewall\ByUsernameProvider' shared autowired service.

return $this->services['Rialto\\Security\\Firewall\\ByUsernameProvider'] = new \Rialto\Security\Firewall\ByUsernameProvider(${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'});
