<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Security\Firewall\ByUuidProvider' shared autowired service.

return $this->services['Rialto\\Security\\Firewall\\ByUuidProvider'] = new \Rialto\Security\Firewall\ByUuidProvider(${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'});
