<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Fabiang\Xmpp\Client' shared autowired service.

$a = new \Fabiang\Xmpp\Options('tls://talk.google.com:5223');
$a->setUsername('bob.t.erbauer');
$a->setPassword('');
$a->setTo('gmail.com');
$a->setTimeout(10);

return $this->services['Fabiang\\Xmpp\\Client'] = new \Fabiang\Xmpp\Client($a);
