<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Sales\Order\Allocation\Command\CreateStockItemOrderHandler' shared autowired service.

return $this->services['Rialto\\Sales\\Order\\Allocation\\Command\\CreateStockItemOrderHandler'] = new \Rialto\Sales\Order\Allocation\Command\CreateStockItemOrderHandler(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Purchasing\\Order\\PurchaseOrderFactory']) ? $this->services['Rialto\\Purchasing\\Order\\PurchaseOrderFactory'] : $this->load('getPurchaseOrderFactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Purchasing\\Producer\\StockProducerFactory']) ? $this->services['Rialto\\Purchasing\\Producer\\StockProducerFactory'] : $this->load('getStockProducerFactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'});
