<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Purchasing\Order\Web\CreatePurchaseOrderType' shared autowired service.

return $this->services['Rialto\\Purchasing\\Order\\Web\\CreatePurchaseOrderType'] = new \Rialto\Purchasing\Order\Web\CreatePurchaseOrderType(${($_ = isset($this->services['Rialto\\Purchasing\\Order\\PurchaseOrderFactory']) ? $this->services['Rialto\\Purchasing\\Order\\PurchaseOrderFactory'] : $this->load('getPurchaseOrderFactoryService.php')) && false ?: '_'});
