<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.rialto_printing_job_cli_deletecompletedprintjobs' shared autowired service.

return $this->services['console.command.rialto_printing_job_cli_deletecompletedprintjobs'] = new \Rialto\Printing\Job\Cli\DeleteCompletedPrintJobs(${($_ = isset($this->services['Rialto\\Printing\\Job\\PrintQueue']) ? $this->services['Rialto\\Printing\\Job\\PrintQueue'] : $this->load('getPrintQueueService.php')) && false ?: '_'});
