<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.rialto_purchasing_recurring_cli_autoinvoicecommand' shared autowired service.

return $this->services['console.command.rialto_purchasing_recurring_cli_autoinvoicecommand'] = new \Rialto\Purchasing\Recurring\Cli\AutoInvoiceCommand(${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Email\\MailerInterface']) ? $this->services['Rialto\\Email\\MailerInterface'] : $this->load('getMailerInterfaceService.php')) && false ?: '_'}, ${($_ = isset($this->services['validator']) ? $this->services['validator'] : $this->getValidatorService()) && false ?: '_'});
