<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Sales\Order\CustomerPartNoPopulator' shared autowired service.

return $this->services['Rialto\\Sales\\Order\\CustomerPartNoPopulator'] = new \Rialto\Sales\Order\CustomerPartNoPopulator(${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'});
