<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Purchasing\Manufacturer\ComplianceFilesystem' shared autowired service.

return $this->services['Rialto\\Purchasing\\Manufacturer\\ComplianceFilesystem'] = new \Rialto\Purchasing\Manufacturer\ComplianceFilesystem(${($_ = isset($this->services['Gumstix\\Storage\\FileStorage']) ? $this->services['Gumstix\\Storage\\FileStorage'] : $this->getFileStorageService()) && false ?: '_'});
