<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\PcbNg\Command\CreateManufacturedStockItemPcbNgPurchasingDataHandler' shared autowired service.

$a = ${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'};
$b = ${($_ = isset($this->services['Rialto\\PcbNg\\Service\\PcbNgClient']) ? $this->services['Rialto\\PcbNg\\Service\\PcbNgClient'] : $this->load('getPcbNgClientService.php')) && false ?: '_'};

return $this->services['Rialto\\PcbNg\\Command\\CreateManufacturedStockItemPcbNgPurchasingDataHandler'] = new \Rialto\PcbNg\Command\CreateManufacturedStockItemPcbNgPurchasingDataHandler($a, new \Rialto\PcbNg\Service\PcbNgPurchasingDataFactory($a, $b, ${($_ = isset($this->services['Rialto\\PcbNg\\Service\\GerbersConverter']) ? $this->services['Rialto\\PcbNg\\Service\\GerbersConverter'] : ($this->services['Rialto\\PcbNg\\Service\\GerbersConverter'] = new \Rialto\PcbNg\Service\GerbersConverter())) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\PcbNg\\Service\\LocationsConverter']) ? $this->services['Rialto\\PcbNg\\Service\\LocationsConverter'] : ($this->services['Rialto\\PcbNg\\Service\\LocationsConverter'] = new \Rialto\PcbNg\Service\LocationsConverter())) && false ?: '_'}, ${($_ = isset($this->services['Gumstix\\Storage\\FileStorage']) ? $this->services['Gumstix\\Storage\\FileStorage'] : $this->getFileStorageService()) && false ?: '_'}), $b, ${($_ = isset($this->services['validator']) ? $this->services['validator'] : $this->getValidatorService()) && false ?: '_'});
