<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.rialto_stock_item_cli_bulksetdefaultworkordercommand' shared autowired service.

return $this->services['console.command.rialto_stock_item_cli_bulksetdefaultworkordercommand'] = new \Rialto\Stock\Item\Cli\BulkSetDefaultWorkOrderCommand(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, new \Rialto\Geppetto\GeppettoClient(${($_ = isset($this->services['Gumstix\\SSOBundle\\Service\\HttpClientFactory']) ? $this->services['Gumstix\\SSOBundle\\Service\\HttpClientFactory'] : $this->load('getHttpClientFactoryService.php')) && false ?: '_'}, 'http://geppetto.mystix.com'));
