<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.rialto_tax_regime_cli_loadtaxregimescommand' shared autowired service.

return $this->services['console.command.rialto_tax_regime_cli_loadtaxregimescommand'] = new \Rialto\Tax\Regime\Cli\LoadTaxRegimesCommand(${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'});
