<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.rialto_stock_level_cli_stocklevelsynccommand' shared autowired service.

return $this->services['console.command.rialto_stock_level_cli_stocklevelsynccommand'] = new \Rialto\Stock\Level\Cli\StockLevelSyncCommand(${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Stock\\Level\\StockLevelSynchronizer']) ? $this->services['Rialto\\Stock\\Level\\StockLevelSynchronizer'] : $this->load('getStockLevelSynchronizerService.php')) && false ?: '_'}, ${($_ = isset($this->services['monolog.logger.automation']) ? $this->services['monolog.logger.automation'] : $this->load('getMonolog_Logger_AutomationService.php')) && false ?: '_'});
