<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Ciiva\CiivaClient' shared autowired service.

return $this->services['Rialto\\Ciiva\\CiivaClient'] = new \Rialto\Ciiva\CiivaClient(new \GuzzleHttp\Client(), '', '', ($this->targetDirs[4].'/app/../var/ciivaCookies'));
