<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.rialto_manufacturing_customization_cli_validatesubstitutionscommand' shared autowired service.

return $this->services['console.command.rialto_manufacturing_customization_cli_validatesubstitutionscommand'] = new \Rialto\Manufacturing\Customization\Cli\ValidateSubstitutionsCommand();
