<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.rialto_manufacturing_kit_reminder_sendemailcommand' shared autowired service.

$a = ${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'};

return $this->services['console.command.rialto_manufacturing_kit_reminder_sendemailcommand'] = new \Rialto\Manufacturing\Kit\Reminder\SendEmailCommand($a->getRepository('Rialto\\Stock\\Transfer\\Transfer'), $a->getRepository('Rialto\\Security\\User\\User'), ${($_ = isset($this->services['Rialto\\Email\\MailerInterface']) ? $this->services['Rialto\\Email\\MailerInterface'] : $this->load('getMailerInterfaceService.php')) && false ?: '_'}, ${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->load('getLogger2Service.php')) && false ?: '_'});
