<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.rialto_purchasing_order_cli_autoordercommand' shared autowired service.

return $this->services['console.command.rialto_purchasing_order_cli_autoordercommand'] = new \Rialto\Purchasing\Order\Cli\AutoOrderCommand();
