<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'craue.form.flow.data_manager' shared service.

return $this->services['craue.form.flow.data_manager'] = new \Craue\FormFlowBundle\Storage\DataManager(${($_ = isset($this->services['craue.form.flow.storage']) ? $this->services['craue.form.flow.storage'] : $this->load('getCraue_Form_Flow_StorageService.php')) && false ?: '_'});
