<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Sales\DocumentEventListener' shared autowired service.

return $this->services['Rialto\\Sales\\DocumentEventListener'] = new \Rialto\Sales\DocumentEventListener(${($_ = isset($this->services['Rialto\\Shipping\\Shipment\\ShipmentFactory']) ? $this->services['Rialto\\Shipping\\Shipment\\ShipmentFactory'] : $this->load('getShipmentFactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Sales\\SalesPrintManager']) ? $this->services['Rialto\\Sales\\SalesPrintManager'] : $this->load('getSalesPrintManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Stock\\Publication\\PublicationPrintManager']) ? $this->services['Rialto\\Stock\\Publication\\PublicationPrintManager'] : $this->load('getPublicationPrintManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['monolog.logger.flash']) ? $this->services['monolog.logger.flash'] : $this->load('getMonolog_Logger_FlashService.php')) && false ?: '_'});
