<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Allocation\Allocation\EmptyAllocationRemover' shared autowired service.

return $this->services['Rialto\\Allocation\\Allocation\\EmptyAllocationRemover'] = new \Rialto\Allocation\Allocation\EmptyAllocationRemover(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'});
