<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Cms\ExceptionHandler' shared autowired service.

return $this->services['Rialto\\Cms\\ExceptionHandler'] = new \Rialto\Cms\ExceptionHandler(${($_ = isset($this->services['security.authorization_checker']) ? $this->services['security.authorization_checker'] : $this->getSecurity_AuthorizationCheckerService()) && false ?: '_'}, ${($_ = isset($this->services['Symfony\\Component\\Routing\\RouterInterface']) ? $this->services['Symfony\\Component\\Routing\\RouterInterface'] : $this->getRouterInterfaceService()) && false ?: '_'});
