<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Purchasing\Order\Web\EditPurchaseOrderType' shared autowired service.

return $this->services['Rialto\\Purchasing\\Order\\Web\\EditPurchaseOrderType'] = new \Rialto\Purchasing\Order\Web\EditPurchaseOrderType(${($_ = isset($this->services['security.authorization_checker']) ? $this->services['security.authorization_checker'] : $this->getSecurity_AuthorizationCheckerService()) && false ?: '_'});
