<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Sales\EmailEventListener' shared autowired service.

return $this->services['Rialto\\Sales\\EmailEventListener'] = new \Rialto\Sales\EmailEventListener(${($_ = isset($this->services['Rialto\\Email\\MailerInterface']) ? $this->services['Rialto\\Email\\MailerInterface'] : $this->load('getMailerInterfaceService.php')) && false ?: '_'}, ${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Sales\\SalesPdfGenerator']) ? $this->services['Rialto\\Sales\\SalesPdfGenerator'] : $this->load('getSalesPdfGeneratorService.php')) && false ?: '_'});
