<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Manufacturing\Kit\Reminder\EmailScheduler' shared autowired service.

return $this->services['Rialto\\Manufacturing\\Kit\\Reminder\\EmailScheduler'] = new \Rialto\Manufacturing\Kit\Reminder\EmailScheduler(${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'});
