<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Stock\EmailEventListener' shared autowired service.

return $this->services['Rialto\\Stock\\EmailEventListener'] = new \Rialto\Stock\EmailEventListener(${($_ = isset($this->services['Rialto\\Email\\MailerInterface']) ? $this->services['Rialto\\Email\\MailerInterface'] : $this->load('getMailerInterfaceService.php')) && false ?: '_'}, ${($_ = isset($this->services['security.token_storage']) ? $this->services['security.token_storage'] : ($this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage())) && false ?: '_'}, ${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'});
