<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Madison\Feature\FeatureInjector' shared autowired service.

return $this->services['Rialto\\Madison\\Feature\\FeatureInjector'] = new \Rialto\Madison\Feature\FeatureInjector(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Madison\\Feature\\Repository\\StockItemFeatureRepository']) ? $this->services['Rialto\\Madison\\Feature\\Repository\\StockItemFeatureRepository'] : $this->load('getStockItemFeatureRepositoryService.php')) && false ?: '_'});
