<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Madison\Feature\Web\FeatureType' shared autowired service.

return $this->services['Rialto\\Madison\\Feature\\Web\\FeatureType'] = new \Rialto\Madison\Feature\Web\FeatureType(${($_ = isset($this->services['Rialto\\Madison\\MadisonClient']) ? $this->services['Rialto\\Madison\\MadisonClient'] : $this->load('getMadisonClientService.php')) && false ?: '_'});
