<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_rest.serializer' shared service.

if ($lazyLoad) {
    return $this->services['fos_rest.serializer'] = $this->createProxy('SymfonySerializerAdapter_0141a64', function () {
        return \SymfonySerializerAdapter_0141a64::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getFosRest_SerializerService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

return new \FOS\RestBundle\Serializer\SymfonySerializerAdapter(${($_ = isset($this->services['serializer']) ? $this->services['serializer'] : $this->load('getSerializerService.php')) && false ?: '_'});
