<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_rest.view_handler' shared autowired service.

return $this->services['fos_rest.view_handler'] = new \Rialto\Web\Serializer\ViewHandler(${($_ = isset($this->services['FOS\\RestBundle\\View\\ViewHandlerInterface']) ? $this->services['FOS\\RestBundle\\View\\ViewHandlerInterface'] : $this->load('getViewHandlerInterfaceService.php')) && false ?: '_'}, ${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())) && false ?: '_'});
