<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Purchasing\Receiving\GoodsReceivedLogger' shared autowired service.

return $this->services['Rialto\\Purchasing\\Receiving\\GoodsReceivedLogger'] = new \Rialto\Purchasing\Receiving\GoodsReceivedLogger(${($_ = isset($this->services['monolog.logger.receiving']) ? $this->services['monolog.logger.receiving'] : $this->load('getMonolog_Logger_ReceivingService.php')) && false ?: '_'});
