<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Purchasing\Receiving\Web\GoodsReceivedType' shared autowired service.

return $this->services['Rialto\\Purchasing\\Receiving\\Web\\GoodsReceivedType'] = new \Rialto\Purchasing\Receiving\Web\GoodsReceivedType(${($_ = isset($this->services['security.authorization_checker']) ? $this->services['security.authorization_checker'] : $this->getSecurity_AuthorizationCheckerService()) && false ?: '_'});
