<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gumstix_sso.credential_storage_database' shared service.

return $this->services['gumstix_sso.credential_storage_database'] = new \Gumstix\SSOBundle\Service\DoctrineCredentialStorage(${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'});
