<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Gumstix\SSOBundle\Security\HeaderAuthenticator' shared service.

return $this->services['Gumstix\\SSOBundle\\Security\\HeaderAuthenticator'] = new \Gumstix\SSOBundle\Security\HeaderAuthenticator(${($_ = isset($this->services['Gumstix\\SSO\\Service\\SingleSignOn']) ? $this->services['Gumstix\\SSO\\Service\\SingleSignOn'] : $this->load('getSingleSignOnService.php')) && false ?: '_'}, ${($_ = isset($this->services['security.token_storage']) ? $this->services['security.token_storage'] : ($this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage())) && false ?: '_'});
