<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Ups\Invoice\InvoiceLoader' shared autowired service.

$this->services['Rialto\\Ups\\Invoice\\InvoiceLoader'] = $instance = new \Rialto\Ups\Invoice\InvoiceLoader('ftp2.ups.com', 'gumstix0316', '');

$a = ${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'};

$instance->registerParser(new \Rialto\Ups\Invoice\XmlInvoiceParser($a, 108));
$instance->registerParser(new \Rialto\Ups\Invoice\CsvInvoiceParser($a, 108));

return $instance;
