<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Stock\Item\Version\Web\ItemVersionSelectorType' shared autowired service.

return $this->services['Rialto\\Stock\\Item\\Version\\Web\\ItemVersionSelectorType'] = new \Rialto\Stock\Item\Version\Web\ItemVersionSelectorType(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}->getRepository('Rialto\\Stock\\Item\\Version\\ItemVersion'));
