<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'jms_job_queue.entity.statistics_listener' shared service.

return $this->services['jms_job_queue.entity.statistics_listener'] = new \JMS\JobQueueBundle\Entity\Listener\StatisticsListener();
