<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'jms_job_queue.command.schedule' shared service.

$this->services['jms_job_queue.command.schedule'] = $instance = new \JMS\JobQueueBundle\Command\ScheduleCommand(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, new RewindableGenerator(function () {
    return new \EmptyIterator();
}, 0), new RewindableGenerator(function () {
    return new \EmptyIterator();
}, 0));

$instance->setName('jms-job-queue:schedule');

return $instance;
