<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'jms_job_queue.retry_scheduler' shared service.

return $this->services['jms_job_queue.retry_scheduler'] = new \JMS\JobQueueBundle\Retry\ExponentialRetryScheduler();
