<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'jms_job_queue.job_manager' shared service.

return $this->services['jms_job_queue.job_manager'] = new \JMS\JobQueueBundle\Entity\Repository\JobManager(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'}, ${($_ = isset($this->services['jms_job_queue.retry_scheduler']) ? $this->services['jms_job_queue.retry_scheduler'] : ($this->services['jms_job_queue.retry_scheduler'] = new \JMS\JobQueueBundle\Retry\ExponentialRetryScheduler())) && false ?: '_'});
