<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Purchasing\LeadTime\LeadTimeCalculator' shared autowired service.

return $this->services['Rialto\\Purchasing\\LeadTime\\LeadTimeCalculator'] = new \Rialto\Purchasing\LeadTime\LeadTimeCalculator(new \Rialto\Purchasing\LeadTime\LeadTimeGateway(${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Stock\\Level\\StockLevelService']) ? $this->services['Rialto\\Stock\\Level\\StockLevelService'] : $this->load('getStockLevelServiceService.php')) && false ?: '_'}));
