<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Stock\Bin\Label\Web\LabelController' shared autowired service.

return $this->services['Rialto\\Stock\\Bin\\Label\\Web\\LabelController'] = new \Rialto\Stock\Bin\Label\Web\LabelController();
