<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Gumstix\SSOBundle\Security\LoginAuthenticator' shared service.

return $this->services['Gumstix\\SSOBundle\\Security\\LoginAuthenticator'] = new \Gumstix\SSOBundle\Security\LoginAuthenticator(${($_ = isset($this->services['gumstix_sso.router']) ? $this->services['gumstix_sso.router'] : ($this->services['gumstix_sso.router'] = new \Gumstix\SSOBundle\Service\SSORouter('http://accounts.mystix.com/'))) && false ?: '_'});
