<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Panelization\Layout\Layout' shared autowired service.

return $this->services['Rialto\\Panelization\\Layout\\Layout'] = new \Rialto\Panelization\Layout\TopToBottomLayout();
