<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Gumstix\SSOBundle\Service\LogoutService' shared service.

return $this->services['Gumstix\\SSOBundle\\Service\\LogoutService'] = new \Gumstix\SSOBundle\Service\LogoutService('http://accounts.mystix.com/');
