<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'monolog.handler.production' shared service.

$this->services['monolog.handler.production'] = $instance = new \Monolog\Handler\StreamHandler(($this->targetDirs[3].'/logs/www-data/production.log'), 200, true, NULL, false);

$instance->pushProcessor(${($_ = isset($this->services['monolog.processor.psr_log_message']) ? $this->services['monolog.processor.psr_log_message'] : ($this->services['monolog.processor.psr_log_message'] = new \Monolog\Processor\PsrLogMessageProcessor())) && false ?: '_'});
$instance->pushProcessor([0 => new \Rialto\Manufacturing\Log\ProductionLogProcessor(${($_ = isset($this->services['security.token_storage']) ? $this->services['security.token_storage'] : ($this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage())) && false ?: '_'}), 1 => 'processRecord']);

return $instance;
