<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Madison\MadisonClient' shared autowired service.

return $this->services['Rialto\\Madison\\MadisonClient'] = new \Rialto\Madison\MadisonClient(${($_ = isset($this->services['Gumstix\\SSOBundle\\Service\\HttpClientFactory']) ? $this->services['Gumstix\\SSOBundle\\Service\\HttpClientFactory'] : $this->load('getHttpClientFactoryService.php')) && false ?: '_'}, 'http://madison.mystix.com/app.php', new \Rialto\Madison\Link\LinkFactory());
