<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Shopify\Order\OrderClosedListener' shared autowired service.

return $this->services['Rialto\\Shopify\\Order\\OrderClosedListener'] = new \Rialto\Shopify\Order\OrderClosedListener(${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'}, new \GuzzleHttp\Client());
