<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Sales\Order\Import\OrderImporter' shared autowired service.

return $this->services['Rialto\\Sales\\Order\\Import\\OrderImporter'] = new \Rialto\Sales\Order\Import\OrderImporter(new \Rialto\Sales\Order\Import\OrderImporterDataSource(${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'}));
