<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Sales\Order\Email\OrderEmailListener' shared autowired service.

return $this->services['Rialto\\Sales\\Order\\Email\\OrderEmailListener'] = new \Rialto\Sales\Order\Email\OrderEmailListener(${($_ = isset($this->services['Rialto\\Email\\MailerInterface']) ? $this->services['Rialto\\Email\\MailerInterface'] : $this->load('getMailerInterfaceService.php')) && false ?: '_'}, ${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'}, 'andrew.simpson', ${($_ = isset($this->services['Rialto\\Sales\\Order\\Email\\OrderToEmailFilter']) ? $this->services['Rialto\\Sales\\Order\\Email\\OrderToEmailFilter'] : $this->load('getOrderToEmailFilterService.php')) && false ?: '_'});
