<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Magento2\Order\OrderSynchronizerInterface' shared autowired service.

return $this->services['Rialto\\Magento2\\Order\\OrderSynchronizerInterface'] = new \Rialto\Magento2\Order\OrderSynchronizer(${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Magento2\\Api\\Rest\\RestApiFactory']) ? $this->services['Rialto\\Magento2\\Api\\Rest\\RestApiFactory'] : $this->load('getRestApiFactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Sales\\Order\\Import\\OrderImporter']) ? $this->services['Rialto\\Sales\\Order\\Import\\OrderImporter'] : $this->load('getOrderImporterService.php')) && false ?: '_'});
