<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\PcbNg\Service\PickAndPlaceFactory' shared autowired service.

return $this->services['Rialto\\PcbNg\\Service\\PickAndPlaceFactory'] = new \Rialto\PcbNg\Service\PickAndPlaceFactory(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}->getRepository('Rialto\\Purchasing\\Catalog\\PurchasingData'), ${($_ = isset($this->services['Gumstix\\Storage\\FileStorage']) ? $this->services['Gumstix\\Storage\\FileStorage'] : $this->getFileStorageService()) && false ?: '_'});
