<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Stock\Publication\PublicationFilesystem' shared autowired service.

return $this->services['Rialto\\Stock\\Publication\\PublicationFilesystem'] = new \Rialto\Stock\Publication\PublicationFilesystem(${($_ = isset($this->services['Gumstix\\Storage\\FileStorage']) ? $this->services['Gumstix\\Storage\\FileStorage'] : $this->getFileStorageService()) && false ?: '_'});
