<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Purchasing\Order\Web\PurchaseOrderController' shared autowired service.

return $this->services['Rialto\\Purchasing\\Order\\Web\\PurchaseOrderController'] = new \Rialto\Purchasing\Order\Web\PurchaseOrderController(${($_ = isset($this->services['Rialto\\Purchasing\\Order\\PurchaseOrderSender']) ? $this->services['Rialto\\Purchasing\\Order\\PurchaseOrderSender'] : $this->load('getPurchaseOrderSenderService.php')) && false ?: '_'}, ${($_ = isset($this->services['validator']) ? $this->services['validator'] : $this->getValidatorService()) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Port\\CommandBus\\CommandBus']) ? $this->services['Rialto\\Port\\CommandBus\\CommandBus'] : $this->load('getCommandBusService.php')) && false ?: '_'}, ${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Gumstix\\Storage\\FileStorage']) ? $this->services['Gumstix\\Storage\\FileStorage'] : $this->getFileStorageService()) && false ?: '_'});
