<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Allocation\Validator\PurchasingDataExistsForChildValidator' shared autowired service.

return $this->services['Rialto\\Allocation\\Validator\\PurchasingDataExistsForChildValidator'] = new \Rialto\Allocation\Validator\PurchasingDataExistsForChildValidator(${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'});
