<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Panelization\Web\PanelPdfGenerator' shared autowired service.

return $this->services['Rialto\\Panelization\\Web\\PanelPdfGenerator'] = new \Rialto\Panelization\Web\PanelPdfGenerator(${($_ = isset($this->services['Rialto\\Filetype\\Pdf\\PdfGenerator']) ? $this->services['Rialto\\Filetype\\Pdf\\PdfGenerator'] : $this->load('getPdfGeneratorService.php')) && false ?: '_'});
