<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'autowired.Rialto\Stock\Item\PurchasedStockItem' shared autowired service.

return $this->services['autowired.Rialto\\Stock\\Item\\PurchasedStockItem'] = new \Rialto\Stock\Item\PurchasedStockItem();
