<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Catalina\ProductionTaskListener' shared autowired service.

return $this->services['Rialto\\Catalina\\ProductionTaskListener'] = new \Rialto\Catalina\ProductionTaskListener(${($_ = isset($this->services['Rialto\\Catalina\\CatalinaClient']) ? $this->services['Rialto\\Catalina\\CatalinaClient'] : $this->load('getCatalinaClientService.php')) && false ?: '_'}, ${($_ = isset($this->services['monolog.logger.manufacturing']) ? $this->services['monolog.logger.manufacturing'] : $this->load('getMonolog_Logger_ManufacturingService.php')) && false ?: '_'});
