<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Panelization\IO\PanelizationStorage' shared autowired service.

return $this->services['Rialto\\Panelization\\IO\\PanelizationStorage'] = new \Rialto\Panelization\IO\PanelizationStorage(${($_ = isset($this->services['Gumstix\\Storage\\FileStorage']) ? $this->services['Gumstix\\Storage\\FileStorage'] : $this->getFileStorageService()) && false ?: '_'});
