<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Purchasing\Order\Attachment\PurchaseOrderAttachmentGenerator' shared autowired service.

return $this->services['Rialto\\Purchasing\\Order\\Attachment\\PurchaseOrderAttachmentGenerator'] = new \Rialto\Purchasing\Order\Attachment\PurchaseOrderAttachmentGenerator(${($_ = isset($this->services['Rialto\\Purchasing\\Order\\Attachment\\PurchaseOrderAttachmentLocator']) ? $this->services['Rialto\\Purchasing\\Order\\Attachment\\PurchaseOrderAttachmentLocator'] : $this->load('getPurchaseOrderAttachmentLocatorService.php')) && false ?: '_'});
