<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Filetype\Pdf\PdfGenerator' shared autowired service.

return $this->services['Rialto\\Filetype\\Pdf\\PdfGenerator'] = new \Rialto\Filetype\Pdf\PdfGenerator(${($_ = isset($this->services['templating']) ? $this->services['templating'] : $this->load('getTemplatingService.php')) && false ?: '_'});
