<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Purchasing\Catalog\Command\RefreshPurchasingDataStockLevelHandler' shared autowired service.

return $this->services['Rialto\\Purchasing\\Catalog\\Command\\RefreshPurchasingDataStockLevelHandler'] = new \Rialto\Purchasing\Catalog\Command\RefreshPurchasingDataStockLevelHandler(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Purchasing\\Catalog\\PurchasingDataSynchronizer']) ? $this->services['Rialto\\Purchasing\\Catalog\\PurchasingDataSynchronizer'] : $this->load('getPurchasingDataSynchronizerService.php')) && false ?: '_'});
