<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Magento2\Api\Rest\RestApiFactory' shared autowired service.

return $this->services['Rialto\\Magento2\\Api\\Rest\\RestApiFactory'] = new \Rialto\Magento2\Api\Rest\RestApiFactory(${($_ = isset($this->services['JMS\\Serializer\\SerializerInterface']) ? $this->services['JMS\\Serializer\\SerializerInterface'] : $this->load('getSerializerInterfaceService.php')) && false ?: '_'}, ${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->load('getLogger2Service.php')) && false ?: '_'});
