<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Purchasing\Receiving\Receiver' shared autowired service.

$a = ${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'};
$b = ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'};
$c = ${($_ = isset($this->services['monolog.logger.flash']) ? $this->services['monolog.logger.flash'] : $this->load('getMonolog_Logger_FlashService.php')) && false ?: '_'};

return $this->services['Rialto\\Purchasing\\Receiving\\Receiver'] = new \Rialto\Purchasing\Receiving\Receiver(new \Rialto\Purchasing\Receiving\ItemReceiver($a, $b, ${($_ = isset($this->services['Rialto\\Manufacturing\\WorkOrder\\Issue\\WorkOrderIssuer']) ? $this->services['Rialto\\Manufacturing\\WorkOrder\\Issue\\WorkOrderIssuer'] : $this->load('getWorkOrderIssuerService.php')) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Allocation\\Allocation\\AllocationFactory']) ? $this->services['Rialto\\Allocation\\Allocation\\AllocationFactory'] : ($this->services['Rialto\\Allocation\\Allocation\\AllocationFactory'] = new \Rialto\Allocation\Allocation\AllocationFactory())) && false ?: '_'}, $c), $a, $b, $c);
