<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Stock\Item\Command\RefreshStockLevelHandler' shared autowired service.

return $this->services['Rialto\\Stock\\Item\\Command\\RefreshStockLevelHandler'] = new \Rialto\Stock\Item\Command\RefreshStockLevelHandler(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Stock\\Level\\StockLevelSynchronizer']) ? $this->services['Rialto\\Stock\\Level\\StockLevelSynchronizer'] : $this->load('getStockLevelSynchronizerService.php')) && false ?: '_'});
