<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.5h4cvxx' shared service.

return $this->services['service_locator.5h4cvxx'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['transfer' => function () {
    $f = function (\Rialto\Accounting\Bank\Transfer\BankTransfer $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.Rialto\\Accounting\\Bank\\Transfer\\BankTransfer']) ? $this->services['autowired.Rialto\\Accounting\\Bank\\Transfer\\BankTransfer'] : ($this->services['autowired.Rialto\\Accounting\\Bank\\Transfer\\BankTransfer'] = new \Rialto\Accounting\Bank\Transfer\BankTransfer())) && false ?: '_'});
}]);
