<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator._ayg34g' shared service.

return $this->services['service_locator._ayg34g'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['pcbNgClient' => function () {
    $f = function (\Rialto\PcbNg\Service\PcbNgClient $v = null) { return $v; }; return $f(${($_ = isset($this->services['Rialto\\PcbNg\\Service\\PcbNgClient']) ? $this->services['Rialto\\PcbNg\\Service\\PcbNgClient'] : $this->load('getPcbNgClientService.php')) && false ?: '_'});
}]);
