<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Sales\SalesPdfGenerator' shared autowired service.

$a = ${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'};

return $this->services['Rialto\\Sales\\SalesPdfGenerator'] = new \Rialto\Sales\SalesPdfGenerator(new \Rialto\Filing\DocumentGenerator($a, ${($_ = isset($this->services['Rialto\\Filing\\DocumentFilesystem']) ? $this->services['Rialto\\Filing\\DocumentFilesystem'] : $this->load('getDocumentFilesystemService.php')) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Filetype\\Postscript\\FontFilesystem']) ? $this->services['Rialto\\Filetype\\Postscript\\FontFilesystem'] : ($this->services['Rialto\\Filetype\\Postscript\\FontFilesystem'] = new \Rialto\Filetype\Postscript\FontFilesystem(($this->targetDirs[4].'/fonts')))) && false ?: '_'}), ${($_ = isset($this->services['Rialto\\Filetype\\Pdf\\PdfGenerator']) ? $this->services['Rialto\\Filetype\\Pdf\\PdfGenerator'] : $this->load('getPdfGeneratorService.php')) && false ?: '_'}, $a);
