<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.tkotenx' shared service.

return $this->services['service_locator.tkotenx'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['invoice' => function () {
    $f = function (\Rialto\Purchasing\Invoice\SupplierInvoice $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.Rialto\\Purchasing\\Invoice\\SupplierInvoice']) ? $this->services['autowired.Rialto\\Purchasing\\Invoice\\SupplierInvoice'] : $this->load('getSupplierInvoiceService.php')) && false ?: '_'});
}]);
