<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.listener.guard.api' shared service.

return $this->services['security.authentication.listener.guard.api'] = new \Symfony\Component\Security\Guard\Firewall\GuardAuthenticationListener(${($_ = isset($this->services['security.authentication.guard_handler']) ? $this->services['security.authentication.guard_handler'] : $this->load('getSecurity_Authentication_GuardHandlerService.php')) && false ?: '_'}, ${($_ = isset($this->services['security.authentication.manager']) ? $this->services['security.authentication.manager'] : $this->getSecurity_Authentication_ManagerService()) && false ?: '_'}, 'api', new RewindableGenerator(function () {
    yield 0 => ${($_ = isset($this->services['Gumstix\\SSOBundle\\Security\\CookieAuthenticator']) ? $this->services['Gumstix\\SSOBundle\\Security\\CookieAuthenticator'] : $this->load('getCookieAuthenticatorService.php')) && false ?: '_'};
    yield 1 => ${($_ = isset($this->services['Gumstix\\SSOBundle\\Security\\HeaderAuthenticator']) ? $this->services['Gumstix\\SSOBundle\\Security\\HeaderAuthenticator'] : $this->load('getHeaderAuthenticatorService.php')) && false ?: '_'};
}, 2), ${($_ = isset($this->services['monolog.logger.security']) ? $this->services['monolog.logger.security'] : $this->load('getMonolog_Logger_SecurityService.php')) && false ?: '_'});
