<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.9.gp1se' shared service.

return $this->services['service_locator.9.gp1se'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['filesystem' => function () {
    $f = function (\Rialto\Purchasing\Invoice\SupplierInvoiceFilesystem $v = null) { return $v; }; return $f(${($_ = isset($this->services['Rialto\\Purchasing\\Invoice\\SupplierInvoiceFilesystem']) ? $this->services['Rialto\\Purchasing\\Invoice\\SupplierInvoiceFilesystem'] : $this->getSupplierInvoiceFilesystemService()) && false ?: '_'});
}, 'supplier' => function () {
    $f = function (\Rialto\Purchasing\Supplier\Supplier $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.Rialto\\Purchasing\\Supplier\\Supplier']) ? $this->services['autowired.Rialto\\Purchasing\\Supplier\\Supplier'] : ($this->services['autowired.Rialto\\Purchasing\\Supplier\\Supplier'] = new \Rialto\Purchasing\Supplier\Supplier())) && false ?: '_'});
}]);
