<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Purchasing\Supplier\SupplierPaymentStatus' shared autowired service.

return $this->services['Rialto\\Purchasing\\Supplier\\SupplierPaymentStatus'] = new \Rialto\Purchasing\Supplier\SupplierPaymentStatus(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'});
