<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.q.pbxzg' shared service.

return $this->services['service_locator.q.pbxzg'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['item' => function () {
    $f = function (\Rialto\Purchasing\Invoice\SupplierInvoiceItem $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.Rialto\\Purchasing\\Invoice\\SupplierInvoiceItem']) ? $this->services['autowired.Rialto\\Purchasing\\Invoice\\SupplierInvoiceItem'] : ($this->services['autowired.Rialto\\Purchasing\\Invoice\\SupplierInvoiceItem'] = new \Rialto\Purchasing\Invoice\SupplierInvoiceItem())) && false ?: '_'});
}]);
