<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Shipping\Shipment\Web\ShipmentOptionsType' shared autowired service.

return $this->services['Rialto\\Shipping\\Shipment\\Web\\ShipmentOptionsType'] = new \Rialto\Shipping\Shipment\Web\ShipmentOptionsType(${($_ = isset($this->services['Rialto\\Shipping\\Shipment\\ShipmentFactory']) ? $this->services['Rialto\\Shipping\\Shipment\\ShipmentFactory'] : $this->load('getShipmentFactoryService.php')) && false ?: '_'});
