<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Gumstix\SSO\Service\SingleSignOn' shared service.

return $this->services['Gumstix\\SSO\\Service\\SingleSignOn'] = new \Gumstix\SSO\Service\SingleSignOn('http://accounts.mystix.com/', ${($_ = isset($this->services['Gumstix\\SSO\\Service\\CredentialStorage']) ? $this->services['Gumstix\\SSO\\Service\\CredentialStorage'] : ($this->services['Gumstix\\SSO\\Service\\CredentialStorage'] = new \Gumstix\SSO\Service\FileCredentialStorage(($this->targetDirs[4].'/app/../var/data/gumstix_sso/credential.data')))) && false ?: '_'});
