<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Purchasing\Invoice\Web\SupplierInvoiceController' shared autowired service.

return $this->services['Rialto\\Purchasing\\Invoice\\Web\\SupplierInvoiceController'] = new \Rialto\Purchasing\Invoice\Web\SupplierInvoiceController();
