<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.antabtk' shared service.

return $this->services['service_locator.antabtk'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['dependencyUpdater' => function () {
    $f = function (\Rialto\Purchasing\Producer\DependencyUpdater $v = null) { return $v; }; return $f(${($_ = isset($this->services['Rialto\\Purchasing\\Producer\\DependencyUpdater']) ? $this->services['Rialto\\Purchasing\\Producer\\DependencyUpdater'] : $this->load('getDependencyUpdaterService.php')) && false ?: '_'});
}]);
