<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'autowired.Rialto\Purchasing\Invoice\SupplierInvoice' shared autowired service.

return $this->services['autowired.Rialto\\Purchasing\\Invoice\\SupplierInvoice'] = new \Rialto\Purchasing\Invoice\SupplierInvoice(${($_ = isset($this->services['autowired.Rialto\\Purchasing\\Supplier\\Supplier']) ? $this->services['autowired.Rialto\\Purchasing\\Supplier\\Supplier'] : ($this->services['autowired.Rialto\\Purchasing\\Supplier\\Supplier'] = new \Rialto\Purchasing\Supplier\Supplier())) && false ?: '_'});
