<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.1ydjmz8' shared service.

return $this->services['service_locator.1ydjmz8'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['item' => function () {
    $f = function (\Rialto\Stock\Item\PurchasedStockItem $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.Rialto\\Stock\\Item\\PurchasedStockItem']) ? $this->services['autowired.Rialto\\Stock\\Item\\PurchasedStockItem'] : ($this->services['autowired.Rialto\\Stock\\Item\\PurchasedStockItem'] = new \Rialto\Stock\Item\PurchasedStockItem())) && false ?: '_'});
}]);
