<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Stock\Item\StockItemDeleteService' shared autowired service.

return $this->services['Rialto\\Stock\\Item\\StockItemDeleteService'] = new \Rialto\Stock\Item\StockItemDeleteService(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'});
