<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Allocation\Consumer\StockConsumerListener' shared autowired service.

return $this->services['Rialto\\Allocation\\Consumer\\StockConsumerListener'] = new \Rialto\Allocation\Consumer\StockConsumerListener();
