<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.provider.simple_preauth.magento2_oauth_callback' shared service.

return $this->services['security.authentication.provider.simple_preauth.magento2_oauth_callback'] = new \Symfony\Component\Security\Core\Authentication\Provider\SimpleAuthenticationProvider(${($_ = isset($this->services['Rialto\\Magento2\\Firewall\\MagentoAuthenticator']) ? $this->services['Rialto\\Magento2\\Firewall\\MagentoAuthenticator'] : ($this->services['Rialto\\Magento2\\Firewall\\MagentoAuthenticator'] = new \Rialto\Magento2\Firewall\MagentoAuthenticator())) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Magento2\\Firewall\\StorefrontUserProvider']) ? $this->services['Rialto\\Magento2\\Firewall\\StorefrontUserProvider'] : $this->load('getStorefrontUserProviderService.php')) && false ?: '_'}, 'magento2_oauth_callback', ${($_ = isset($this->services['security.user_checker']) ? $this->services['security.user_checker'] : ($this->services['security.user_checker'] = new \Symfony\Component\Security\Core\User\UserChecker())) && false ?: '_'});
