<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Sales\Order\SoftwareInvoicer' shared autowired service.

return $this->services['Rialto\\Sales\\Order\\SoftwareInvoicer'] = new \Rialto\Sales\Order\SoftwareInvoicer(${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Sales\\Order\\SalesOrderPaymentProcessor']) ? $this->services['Rialto\\Sales\\Order\\SalesOrderPaymentProcessor'] : $this->load('getSalesOrderPaymentProcessorService.php')) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Sales\\Invoice\\SalesInvoiceProcessor']) ? $this->services['Rialto\\Sales\\Invoice\\SalesInvoiceProcessor'] : $this->load('getSalesInvoiceProcessorService.php')) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Shipping\\Export\\DeniedPartyScreener']) ? $this->services['Rialto\\Shipping\\Export\\DeniedPartyScreener'] : ($this->services['Rialto\\Shipping\\Export\\DeniedPartyScreener'] = new \Rialto\Shipping\Export\FakeDeniedPartyScreener(false))) && false ?: '_'}, ${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->load('getLogger2Service.php')) && false ?: '_'});
