<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Madison\Feature\Repository\StockItemFeatureRepository' shared autowired service.

return $this->services['Rialto\\Madison\\Feature\\Repository\\StockItemFeatureRepository'] = new \Rialto\Madison\Feature\Repository\DQL\DqlStockItemFeatureRepository(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'});
