<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Purchasing\Supplier\Attribute\Web\SupplierAttributeType' shared autowired service.

return $this->services['Rialto\\Purchasing\\Supplier\\Attribute\\Web\\SupplierAttributeType'] = new \Rialto\Purchasing\Supplier\Attribute\Web\SupplierAttributeType();
