<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Stock\Bin\StockBinUpdateListener' shared autowired service.

return $this->services['Rialto\\Stock\\Bin\\StockBinUpdateListener'] = new \Rialto\Stock\Bin\StockBinUpdateListener(${($_ = isset($this->services['Doctrine\\Common\\Persistence\\ObjectManager']) ? $this->services['Doctrine\\Common\\Persistence\\ObjectManager'] : $this->getObjectManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Port\\CommandBus\\CommandBus']) ? $this->services['Rialto\\Port\\CommandBus\\CommandBus'] : $this->load('getCommandBusService.php')) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Logging\\FlashLogger']) ? $this->services['Rialto\\Logging\\FlashLogger'] : $this->load('getFlashLoggerService.php')) && false ?: '_'});
