<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.mh805et' shared service.

return $this->services['service_locator.mh805et'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['queue' => function () {
    $f = function (\Rialto\Stock\Bin\Label\BinLabelPrintQueue $v = null) { return $v; }; return $f(${($_ = isset($this->services['Rialto\\Stock\\Bin\\Label\\BinLabelPrintQueue']) ? $this->services['Rialto\\Stock\\Bin\\Label\\BinLabelPrintQueue'] : $this->load('getBinLabelPrintQueueService.php')) && false ?: '_'});
}]);
