<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Magento2\Order\SuspectedFraudListener' shared autowired service.

return $this->services['Rialto\\Magento2\\Order\\SuspectedFraudListener'] = new \Rialto\Magento2\Order\SuspectedFraudListener(${($_ = isset($this->services['Rialto\\Email\\MailerInterface']) ? $this->services['Rialto\\Email\\MailerInterface'] : $this->load('getMailerInterfaceService.php')) && false ?: '_'});
