<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Supplier\Order\Web\TrackingFacades\SupplierInvoiceTrackingFacadesFactory' shared autowired service.

return $this->services['Rialto\\Supplier\\Order\\Web\\TrackingFacades\\SupplierInvoiceTrackingFacadesFactory'] = new \Rialto\Supplier\Order\Web\TrackingFacades\SupplierInvoiceTrackingFacadesFactory(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['twig']) ? $this->services['twig'] : $this->getTwigService()) && false ?: '_'});
