<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Sales\Order\Dates\TargetShipDateCalculator' shared autowired service.

return $this->services['Rialto\\Sales\\Order\\Dates\\TargetShipDateCalculator'] = new \Rialto\Sales\Order\Dates\TargetShipDateCalculator();
