<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Security\Firewall\UsernameNotFoundExceptionHandler' shared autowired service.

return $this->services['Rialto\\Security\\Firewall\\UsernameNotFoundExceptionHandler'] = new \Rialto\Security\Firewall\UsernameNotFoundExceptionHandler();
