<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Rialto\Madison\Version\VersionChangeNotifier' shared autowired service.

return $this->services['Rialto\\Madison\\Version\\VersionChangeNotifier'] = new \Rialto\Madison\Version\VersionChangeNotifier(${($_ = isset($this->services['Rialto\\Madison\\MadisonClient']) ? $this->services['Rialto\\Madison\\MadisonClient'] : $this->load('getMadisonClientService.php')) && false ?: '_'}, ${($_ = isset($this->services['Rialto\\Madison\\Version\\VersionChangeCache']) ? $this->services['Rialto\\Madison\\Version\\VersionChangeCache'] : ($this->services['Rialto\\Madison\\Version\\VersionChangeCache'] = new \Rialto\Madison\Version\VersionChangeCache())) && false ?: '_'}, ${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->load('getLogger2Service.php')) && false ?: '_'});
