<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'webpack_encore.exception_listener' shared service.

return $this->services['webpack_encore.exception_listener'] = new \Symfony\WebpackEncoreBundle\EventListener\ExceptionListener(${($_ = isset($this->services['webpack_encore.entrypoint_lookup_collection']) ? $this->services['webpack_encore.entrypoint_lookup_collection'] : $this->load('getWebpackEncore_EntrypointLookupCollectionService.php')) && false ?: '_'}, [0 => '_default']);
