<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'webpack_encore.tag_renderer' shared service.

return $this->services['webpack_encore.tag_renderer'] = new \Symfony\WebpackEncoreBundle\Asset\TagRenderer(${($_ = isset($this->services['webpack_encore.entrypoint_lookup_collection']) ? $this->services['webpack_encore.entrypoint_lookup_collection'] : $this->load('getWebpackEncore_EntrypointLookupCollectionService.php')) && false ?: '_'}, ${($_ = isset($this->services['assets.packages']) ? $this->services['assets.packages'] : $this->getAssets_PackagesService()) && false ?: '_'}, []);
