<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Rialto\Purchasing\Receiving\Notify\XmppEventSubscriber' shared autowired service.

return $this->services['Rialto\\Purchasing\\Receiving\\Notify\\XmppEventSubscriber'] = new \Rialto\Purchasing\Receiving\Notify\XmppEventSubscriber(${($_ = isset($this->services['Fabiang\\Xmpp\\Client']) ? $this->services['Fabiang\\Xmpp\\Client'] : $this->load('getClientService.php')) && false ?: '_'}, ${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->load('getLogger2Service.php')) && false ?: '_'});
